# Generated by Django 4.2.4 on 2023-08-04 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Item Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item Price')),
                ('image', models.ImageField(upload_to='items/images/', verbose_name='Item Image')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Merchant')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
