# Generated by Django 4.2.4 on 2023-08-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_stock_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
    ]
