# Generated by Django 4.2.4 on 2023-08-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accept_id',
            field=models.IntegerField(default=0),
        ),
    ]
